routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home.index');
});

Route::get('/faq', function () {
    return view('home.faq');
});

Route::get('/cek-ruang', 'EventController@index')->name('event.index');

Route::group(['prefix' => 'auth', 'namespace' => 'Auth', 'as' => 'auth.'], function () {
    Route::group(['middleware' => 'guest'], function () {
        // Login
        Route::get('login', 'LoginController@showLoginForm')->name('login.form');
        Route::post('login', 'LoginController@login')->name('login');

        // Register
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register.form');
        Route::post('register', 'RegisterController@register')->name('register');

        // Forgot password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('password.forgot.form');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail')->name('password.forgot');

        // Reset Password
        Route::get('reset-password/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('reset-password', 'ResetPasswordController@reset')->name('password.reset');
    });

    Route::group(['middleware' => 'auth'], function () {
        Route::get('logout', function () {
            auth()->logout();
            return redirect()->to('/');
        })->name('logout');
    });
});

Route::group(['middleware' => 'auth', 'prefix' => 'aplikasi', 'as' => 'application.'], function () {
    Route::get('/', 'ApplicationController@index')->name('index');
    Route::get('{application}', 'ApplicationController@show')->name('show');
});

Route::group(['prefix' => 'profil', 'middleware' => 'auth', 'as' => 'profile.'], function () {
    Route::get('/', 'ProfileController@index')->name('index');
    Route::get('edit', 'ProfileController@edit')->name('edit');
    Route::put('edit', 'ProfileController@update')->name('update');
    Route::get('/password/reset', 'ProfileController@resetPasswordForm')->name('password.reset.form');
    Route::post('/password/reset', 'ProfileController@resetPassword')->name('password.reset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/bekerja', 'WorkingController@create')->name('working.create');
    Route::post('/bekerja', 'WorkingController@store')->name('working.store');
    Route::get('/menjadi-relawan', 'VolunteeringController@create')->name('volunteering.create');
    Route::post('/menjadi-relawan', 'VolunteeringController@store')->name('volunteering.store');
    Route::get('/gawe-event', 'EventController@create')->name('event.create');
    Route::post('/gawe-event', 'EventController@store')->name('event.store');
});

resources/views/layouts/components/errors.blade.php
@if(! is_null(session('errors')))
    @if(count(array_filter(array_keys(session('errors')->getBag('default')->toArray()))) < 1)
        <div class="alert alert-danger">
            {{ session('errors')->first() }}
        </div>
    @endif
@endif

resources/views/layouts/components/footer.blade.php
<footer class="py-5">
    <div class="container">
        <hr>
        <h2 class="display mt-5">Tentang</h2>
        <div class="row">
            <div class="col-md-6 mt-5">
                <p>Sebagai bagian dari visi Wali Kota Surabaya, Tri Rismaharini, untuk menjadikan Surabaya sebagai sentra kreatif dan teknologi di tingkat global, KORIDOR merupakan langkah awal untuk membangun dan memperkuat pondasi ekonomi kreatif di tingkat lokal.</p>
                <p>KORIDOR adalah komitmen Pemerintah Kota Surabaya untuk menciptakan ekosistem yang memberdayakan para kreator, inovator, dan entrepreneur lokal untuk menciptakan inovasi dan mampu bersaing di tingkat global.</p>

                <div class="mt-5">
                    <a href="/faq">Pertanyaan yang Sering Diajukan ></a> <br>
                    <a href="{{ route('event.index') }}">Cek Ketersediaan Ruangan ></a>
                </div>
            </div>
            <div class="col-md-5 offset-md-1">
                <img src="{{ asset('img/logo/Space.png') }}" class="img-fluid" style="width: 300px" alt="">
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/components/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="{{ url('/') }}" style="font-weight: 500">
        SPACE
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{ Request::is("/") ? "active" : "" }}">
                    <a class="nav-link" href="/">Beranda <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="/#facilities">Fasilitas</a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="/#activities">Aktifitas</a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="/#galleries">Galeri</a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="/#location">Lokasi</a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="/#partners">Mitra</a>
                </li>
                <li class="nav-item pl-5">
                    <a class="nav-link" href="{{ route('event.index') }}">Cek Ruang</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                @if(auth()->check())
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ auth()->user()->name }}</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('profile.index') }}">Profil</a>
                            <a class="dropdown-item" href="{{ route('application.index') }}">Daftar Aplikasi</a>
                            <div role="separator" class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('auth.logout') }}">Keluar</a>
                        </div>
                    </li>
                @else
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('auth.login.form') }}">Masuk</a>
                </li>
                @endif
            </ul>
        </div>
    </div>
</nav>